#!/bin/sh
set -eu

USER="nagrecv"
GROUP="$USER"

case "${1}" in
        configure)
                adduser \
                        --home /nonexistent \
                        --quiet \
                        --system \
                        --group \
                        --no-create-home \
                        ${USER}
                ;;

        abort-upgrade|abort-remove|abort-deconfigure)
                ;;

        *)
                echo "postinst called with unknown argument \`${1}'" >&2
                exit 1
                ;;
esac

#DEBHELPER#

exit 0
